// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQI6aFfYuOqHCPLG0Zv2I7rVs_qaMeT3M',
    appId: '1:960631525969:web:a47f74a0e3915342ab5e70',
    messagingSenderId: '960631525969',
    projectId: 'campuswap-e6d7a',
    authDomain: 'campuswap-e6d7a.firebaseapp.com',
    storageBucket: 'campuswap-e6d7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdgu7-rP5DQOokpuSYRlGQyli867UxtQ',
    appId: '1:960631525969:android:47044fa735cb7453ab5e70',
    messagingSenderId: '960631525969',
    projectId: 'campuswap-e6d7a',
    storageBucket: 'campuswap-e6d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxFFBL0TTAWi5bTIv3F7V71aGeqlGNpio',
    appId: '1:960631525969:ios:a61546a92d81ef07ab5e70',
    messagingSenderId: '960631525969',
    projectId: 'campuswap-e6d7a',
    storageBucket: 'campuswap-e6d7a.appspot.com',
    androidClientId: '960631525969-r7i6017e9o2cq57ho1kbnpgqpghpah0u.apps.googleusercontent.com',
    iosClientId: '960631525969-nj494q3vjl7619spsu23jie9mbuq8q93.apps.googleusercontent.com',
    iosBundleId: 'com.example.campuswap',
  );

}